config/routes.rb
PlForm::Application.routes.draw do
  resources :portfolios

  resources :skills

  devise_for :users

  get "home/index"
  root :to => 'home#index'
  resources :users do
    collection do
      get :profile
    end
  end

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  attr_accessible :description, :title,:user_id,:avatar
  belongs_to :user
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :name
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :firstname,:lastname,:email,:contact_no, :password, :password_confirmation, :remember_me,:language,:qualification,
  :role,:country,:avatar,:portfolios_attributes
  validates :firstname,:contact_no, presence: true,:length => { :minimum => 3 }
  validates :email,presence: true, uniqueness: true
  has_many :skills,:dependent => :destroy
  has_many :portfolios,:dependent => :destroy
  accepts_nested_attributes_for :skills
  accepts_nested_attributes_for :portfolios
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  # attr_accessible :title, :body

protected
  def email_required?
    false
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:badge)
      where(conditions).where(["lower(badge) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
    render :layout=>'home'
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @portfolios }
    end
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @portfolio }
    end
  end

  # GET /portfolios/new
  # GET /portfolios/new.json
  def new
    @portfolio = Portfolio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @portfolio }
    end
  end

  # GET /portfolios/1/edit
  def edit
    @portfolio = Portfolio.find(params[:id])
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(params[:portfolio])

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render json: @portfolio, status: :created, location: @portfolio }
      else
        format.html { render action: "new" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /portfolios/1
  # PUT /portfolios/1.json
  def update
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio.update_attributes(params[:portfolio])
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skills }
    end
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    @skill = Skill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/new
  # GET /skills/new.json
  def new
    @skill = Skill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/1/edit
  def edit
    @skill = Skill.find(params[:id])
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(params[:skill])

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render json: @skill, status: :created, location: @skill }
      else
        format.html { render action: "new" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /skills/1
  # PUT /skills/1.json
  def update
    @skill = Skill.find(params[:id])

    respond_to do |format|
      if @skill.update_attributes(params[:skill])
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy

    respond_to do |format|
      format.html { redirect_to skills_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user=User.find current_user
    @user.skills.build
    @user.portfolios.build
  end
  def update
    @user=User.find params[:id]
    @user.update_attributes(params[:user])
    redirect_to profile_users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="hero-unit">
  <h1>E-Architect</h1>
  <p>This is a place where you can get the architectural view of your building.You need to provide some information about your area</p>
  <p><a class="btn btn-primary btn-large" href="/users/sign_up">Start and get sample &raquo;</a></p>
  <!-- <p><a href="https://github.com/Eric-Guo/bootstrap-rails-startup-site" target="_blank">Fork this site in Github</a></p>
  <p><a href="http://blog.cloud-mes.com" target="_blank">Visit Author Blog</p> -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap-Rails Startup Site</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <style type="text/css">
    body {padding-top: 80px;}
    </style>
  <![endif]-->
</head>
<body background="../assets/grid-18px-masked.png" style="background-size:100px 800px;">
  <div class="navbar navbar-fixed-top ">
    <div class="navbar-inner ">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/home/index">E-architecture</a>
        <div class="btn-group pull-right">
<% if user_signed_in? %>
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-user"></i> <%= current_user.firstname %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Setting', edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          </ul>
<% else %>
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-minus-sign"></i> Guest
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Register', new_user_registration_path %></li>
          </ul>
<% end %>
        </div>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><a href="/home/index">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
<% if Rails.env == 'development' and request.host == 'localhost' %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Reference Document <b class="caret"></b></a>
              <ul class="dropdown-menu">
<li><a href="http://guides.rubyonrails.org/" target="_black">Rails Guides</a></li>
<li><a href="http://api.rubyonrails.org/" target="_black">Rails API</a></li>
<li><a href="http://www.ruby-doc.org/core/" target="_black">Ruby core</a></li>
<li><a href="http://www.ruby-doc.org/stdlib/" target="_black">Ruby standard library</a></li>
<li><a href="http://apidock.com/rails" target="_black">Rails API dock</a></li>
<li><a href="http://twitter.github.com/bootstrap/components.html" target="_black">Bootstrap reference</a></li>
              </ul>
            </li>
<% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
    <div class="container">
      <div class="row">
      <% if notice.present? %>
        <div class="span8 offset2">
        <div class="alert alert-info">
          <button class="close" data-dismiss="alert">×</button>
          <%= notice %>
        </div>
        </div>
      <% end %>
      <% if alert.present? %>
        <div class="span12 offset2">
        <div class="alert">
          <button class="close" data-dismiss="alert">×</button>
          <%= alert %>
        </div>
        </div>
      <% end %>
      </div><!--/row-->
    </div><!--/.container-->
    <div class="main_container ">
      <%= yield %>      
      
    </div><!--/.fluid-container-->
    <div class="span12">
   <div id="footer">
    <h3>Working in Partnership With:</h3>
    <!-- <div class="thumbnail">  
  </div> -->
    

   </div>
  </div>
</body>
     
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap-Rails Startup Site</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <style type="text/css">
    body {padding-top: 80px;}
    </style>
  <![endif]-->
</head>
<body background="../assets/architechture.jpg">
  <div class="navbar navbar-fixed-top ">
    <div class="navbar-inner ">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">E-architecture</a>
        <div class="btn-group pull-right">
<% if user_signed_in? %>
			<%= image_tag current_user.avatar.url(:thumb) %>
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-user"></i> <%= current_user.firstname %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
          	<li><%= link_to 'Profile', profile_users_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'setting', edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          </ul>
<% else %>
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-minus-sign"></i> Guest
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Register', new_user_registration_path %></li>
          </ul>
<% end %>
        </div>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
<% if Rails.env == 'development' and request.host == 'localhost' %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Reference Document <b class="caret"></b></a>
              <ul class="dropdown-menu">
<li><a href="http://guides.rubyonrails.org/" target="_black">Rails Guides</a></li>
<li><a href="http://api.rubyonrails.org/" target="_black">Rails API</a></li>
<li><a href="http://www.ruby-doc.org/core/" target="_black">Ruby core</a></li>
<li><a href="http://www.ruby-doc.org/stdlib/" target="_black">Ruby standard library</a></li>
<li><a href="http://apidock.com/rails" target="_black">Rails API dock</a></li>
<li><a href="http://twitter.github.com/bootstrap/components.html" target="_black">Bootstrap reference</a></li>
              </ul>
            </li>
<% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
    <div class="container">
      <div class="row">
      <% if notice.present? %>
        <div class="span8 offset2">
        <div class="alert alert-info">
          <button class="close" data-dismiss="alert">×</button>
          <%= notice %>
        </div>
        </div>
      <% end %>
      <% if alert.present? %>
        <div class="span12 offset2">
        <div class="alert">
          <button class="close" data-dismiss="alert">×</button>
          <%= alert %>
        </div>
        </div>
      <% end %>
      </div><!--/row-->
    </div><!--/.container-->
    <div class="container-fluid offset4">
      <%= yield %>      
      
    </div><!--/.fluid-container-->
    <div class="span12">
   <div id="footer">
    <h3>This is home layout:</h3>
    <!-- <div class="thumbnail">  
  </div> -->
    

   </div>
  </div>
</body>
     
</html>

app/views/portfolios/_architect_portfolio.html.erb
<script src="../assets/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
		
		<style type="text/css" media="screen">
			* { margin: 0; padding: 0; }
			
			
			
			h1 { font-family: Georgia; font-style: italic; margin-bottom: 10px; }
			
			h2 {
				font-family: Georgia;
				font-style: italic;
				margin: 25px 0 5px 0;
			}
			
			p { font-size: 1.2em; }
			
			ul li { display: inline; }
			
			.wide {
				border-bottom: 1px #000 solid;
				width: 4000px;
			}
			
			.fleft { float: left; margin: 0 20px 0 0; }
			
			.cboth { clear: both; }			
			#main {
				background: #fff;
				margin: 0 auto;
				padding: 30px;
				width: 1000px;
			}
		</style>
	<body>
		<div>			
			<ul class="gallery clearfix">
				<li><a href="../assets/fullscreen/1.jpg" rel="prettyPhoto[gallery1]" title="You can add caption to pictures. You can add caption to pictures. You can add caption to pictures."><img src="images/thumbnails/t_1.jpg" width="60" height="60" alt="Red round shape" /></a></li>
				<li><a href="../assets/fullscreen/2.jpg" rel="prettyPhoto[gallery1]"><img src="../assets/thumbnails/t_2.jpg" width="60" height="60" alt="Nice building" /></a></li>
				<li><a href="../assets/fullscreen/3.jpg" rel="prettyPhoto[gallery1]"><img src="../assets/thumbnails/t_3.jpg" width="60" height="60" alt="Fire!" /></a></li>
				<li><a href="../assets/fullscreen/4.jpg" rel="prettyPhoto[gallery1]"><img src="../assets/thumbnails/t_4.jpg" width="60" height="60" alt="Rock climbing" /></a></li>
				<li><a href="../assets/fullscreen/5.jpg" rel="prettyPhoto[gallery1]"><img src="../assets/thumbnails/t_5.jpg" width="60" height="60" alt="Fly kite, fly!" /></a></li>
				<li><a href="../assets/fullscreen/6.jpg" rel="prettyPhoto[gallery1]"><img src="../assets/thumbnails/t_2.jpg" width="60" height="60" alt="Nice building" /></a></li>
			</ul>
			<hr />
			<br /><br />
			<script type="text/javascript" charset="utf-8">
			$(document).ready(function(){
				$("area[rel^='prettyPhoto']").prettyPhoto();
				
				$(".gallery:first a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'normal',theme:'light_square',slideshow:3000, autoplay_slideshow: true});
				$(".gallery:gt(0) a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'fast',slideshow:10000, hideflash: true});
		
				$("#custom_content a[rel^='prettyPhoto']:first").prettyPhoto({
					custom_markup: '<div id="map_canvas" style="width:260px; height:265px"></div>',
					changepicturecallback: function(){ initialize(); }
				});

				$("#custom_content a[rel^='prettyPhoto']:last").prettyPhoto({
					custom_markup: '<div id="bsap_1259344" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div><div id="bsap_1237859" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6" style="height:260px"></div><div id="bsap_1251710" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div>',
					changepicturecallback: function(){ _bsap.exec(); }
				});
			});
			</script>
	
			<!-- Google Maps Code -->
			<script type="text/javascript"
			    src="http://maps.google.com/maps/api/js?sensor=true">
			</script>
			<script type="text/javascript">
			  function initialize() {
			    var latlng = new google.maps.LatLng(-34.397, 150.644);
			    var myOptions = {
			      zoom: 8,
			      center: latlng,
			      mapTypeId: google.maps.MapTypeId.ROADMAP
			    };
			    var map = new google.maps.Map(document.getElementById("map_canvas"),
			        myOptions);
			  }

			</script>
			<!-- END Google Maps Code -->
	
			<!-- BuySellAds.com Ad Code -->
			<style type="text/css" media="screen">
				.bsap a { float: left; }
			</style>
			<script type="text/javascript">
			(function(){
			  var bsa = document.createElement('script');
			     bsa.type = 'text/javascript';
			     bsa.async = true;
			     bsa.src = '//s3.buysellads.com/ac/bsa.js';
			  (document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(bsa);
			})();
			</script>
			<!-- END BuySellAds.com Ad Code -->
	</div>

app/views/portfolios/_demo.html.erb
dfdsffdsf

app/views/portfolios/_form.html.erb
<div class="control-group">
 <%= port.label :title%>
 <div class="controls">
<%=port.text_field :title%>
</div></div>
<div class="control-group">
<%= port.label :description%>
<div class="controls">
<%=port.text_field :description%>
</div></div>
<div class="control-group">
<%= port.label :avatar%>
<div class="controls">
<%=port.file_field :avatar%>
</div></div>

app/views/portfolios/edit.html.erb
<h1>Editing portfolio</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<h3>The portfolios records</h3>

<table class="table table-bordered">
  <thread>
  <colgroup>
    <col />
    <col />
    <col class="actions" />
  </colgroup>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
<% @portfolios.each do |portfolio| %>
  <tr>
    <td><%= portfolio.title %></td>
    <td><%= portfolio.description %></td>
    <td><%= link_to 'Show', portfolio %></td>
    <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
    <td><%= link_to 'Destroy', portfolio, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
  </tbody>
</table>
<%= will_paginate @portfolios %>
<br />

<%= link_to 'Input Portfolio', new_portfolio_path, :class => 'btn btn-primary' %>

app/views/portfolios/new.html.erb
<h1>New portfolio</h1>

<%= render 'form' %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @portfolio.title %>
</p>

<p>
  <b>Description:</b>
  <%= @portfolio.description %>
</p>


<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>

app/views/skills/_form.html.erb
<%= simple_form_for(@skill) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<h3>The skills records</h3>

<table class="table table-bordered">
  <thread>
  <colgroup>
    <col />
    <col class="actions" />
  </colgroup>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
<% @skills.each do |skill| %>
  <tr>
    <td><%= skill.name %></td>
    <td><%= link_to 'Show', skill %></td>
    <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
    <td><%= link_to 'Destroy', skill, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
  </tbody>
</table>
<%= will_paginate @skills %>
<br />

<%= link_to 'Input Skill', new_skill_path, :class => 'btn btn-primary' %>

app/views/skills/new.html.erb
<h1>New skill</h1>

<%= render 'form' %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @skill.name %>
</p>


<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>

app/views/users/_attached_document.html.erb
<%unless current_user.skills.empty?%>



<%end%>
  <div class="modal hide fade" id="project-add-modal" style="display: none; ">
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h3>Add New Project</h3>
</div>
<div class="modal-body">
  <form class="form-horizontal">
    <fieldset>
      <div class="control-group">
        <label class="control-label" for="input01">Project Name</label>
        <div class="controls">
          <input type="text" class="input-xlarge" id="project-name">
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="textarea">Project Description</label>
        <div class="controls">
          <textarea class="input-xlarge" id="project-desc" rows="3"></textarea>
        </div>
      </div>
      <label class="control-label">Invite People to
      collaborate on your project</label>
      <div class="control-group">
        <label class="control-label" for="prependedInput"></label>
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on">@</span><input class="span2" id="prependedInput" size="16" type="text">
          </div>
          <p class="help-block">Here's some help text</p>
        </div>
      </div>
    </fieldset>
</form></div>
<div class="modal-footer">
  <a href="#" class="btn btn-danger" data-dismiss="modal">Close</a>
  <a href="#" class="btn btn-primary">Save changes</a>
</div>
  </div>
<div style="text-align: right;"><a class="btn-primary btn" data-toggle="modal" href="#project-add-modal">Add Document</a>
	
</div>

app/views/users/_change_image.html.erb
<style type="text/css" !imortent>
	hr {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    border-image: none;
    border-style: solid none;
    border-width: 1px 0;
    margin: 18px 0;
}
</style>

<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h3>Change Image</h3>
  <hr />
</div>
<div class="modal-body">
	<%=form_for @user do |f| %>
  
    <fieldset>
      <div class="control-group">
        <label class="control-label" for="input01"><%= f.label :avatar %></label>
        <div class="controls">
          <%= f.file_field :avatar %>
        </div>
      </div>
    </fieldset>

</div>
<div class="modal-footer">
  <a href="#" class="btn btn-danger" data-dismiss="modal">Close</a>
  <button type="submit" class="btn btn-primary">Change Image</button>
  
</div>
<%end%>

app/views/users/_experience.html.erb
<%unless current_user.skills.empty?%>



<%end%>
  <div class="modal hide fade" id="project-add-modal" style="display: none; ">
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h3>Add New Project</h3>
</div>
<div class="modal-body">
  <form class="form-horizontal">
    <fieldset>
      <div class="control-group">
        <label class="control-label" for="input01">Project Name</label>
        <div class="controls">
          <input type="text" class="input-xlarge" id="project-name">
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="textarea">Project Description</label>
        <div class="controls">
          <textarea class="input-xlarge" id="project-desc" rows="3"></textarea>
        </div>
      </div>
      <label class="control-label">Invite People to
      collaborate on your project</label>
      <div class="control-group">
        <label class="control-label" for="prependedInput"></label>
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on">@</span><input class="span2" id="prependedInput" size="16" type="text">
          </div>
          <p class="help-block">Here's some help text</p>
        </div>
      </div>
    </fieldset>
</form></div>
<div class="modal-footer">
  <a href="#" class="btn btn-danger" data-dismiss="modal">Close</a>
  <a href="#" class="btn btn-primary">Save changes</a>
</div>
  </div>
<div style="text-align: right;"><a class="btn-primary btn" data-toggle="modal" href="#project-add-modal">Add Experience</a>
	
</div>

app/views/users/_portfolio.html.erb
<%=render '/portfolios/architect_portfolio'%>
<div class="modal hide fade" id="add-portfolio" style="display: none; ">
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h3>Upload Portfolio</h3>
</div>
<div class="modal-body">
 <%=nested_form_for @user,:html=>{:class=>"form-horizontal"} do |f|%>
 <%=f.fields_for :portfolios do |port|%>
<%=render '/portfolios/form',:port=>port%>
   <%= port.link_to_remove "Remove this task" %>
<%end%>     
<p><%= f.link_to_add "Add a task", :portfolios %></p>
   
    
</div>
<div class="modal-footer">
  <a href="#" class="btn btn-danger" data-dismiss="modal">Close</a>
  <button type="submit" class="btn btn-primary">Save</button>
</div>
<%end%>
  </div>
<div style="text-align: right;"><a class="btn-primary btn" data-toggle="modal" href="#add-portfolio">Add Portfolio</a>
	
</div>